### ISSUE TITLE
Not seeing drop list values

### ISSUE THREAD

**Issue by jaychacko** [bcalisto-oshyn/sc-forms-emailsend#1]
Hello great work with this sitecore addon . Having and issue with  drop-down list values via email, Always getting "System.Collections.Generic.List`1[System.String]" instead of selected dropdown value. Any fix for this ?
![image](https://user-images.githubusercontent.com/25227854/55493933-72a5ca00-55ff-11e9-9433-330ef54756c5.png)

**Comment by bcalisto-oshyn** [comment]
Are you using the release version 1.1? Or did you manually compile the project? In theory I already addressed that issue on version 1.1.

**Comment by jaychacko** [comment]
> Are you using the release version 1.1? Or did you manually compile the project? In theory I already addressed that issue on version 1.1.

i downloaded it from the sitecore marketplace a while ago maybe 8  months ago , sitecore market place still have 1.0 version ?
https://marketplace.sitecore.net/Modules/S/Sitecore_Forms_Send_Email_Submit_Action.aspx?sc_lang=en

**Comment by bcalisto-oshyn** [comment]
Sitecore Marketplace download is updated now. Alternatively, you can download version 1.1.0 from here, go to the Code -> Releases section and you'll find the package there. That version should address your issue.

**Comment by jaychacko** [comment]
> Sitecore Marketplace download is updated now. Alternatively, you can download version 1.1.0 from here, go to the Code -> Releases section and you'll find the package there. That version should address your issue.

great thanks ,will give it a try and let you know, any other major update i should see in 1.1.0 ?

**Comment by bcalisto-oshyn** [comment]
> > Sitecore Marketplace download is updated now. Alternatively, you can download version 1.1.0 from here, go to the Code -> Releases section and you'll find the package there. That version should address your issue.
> 
> great thanks ,will give it a try and let you know, any other major update i should see in 1.1.0 ?

No, besides handling the list/dropdown values correctly, and including all required Sitecore items (including the one that was missing in the original release), it doesn't include any other major updates. I've tested this module in Sitecore 9.0.x, but I haven't tested it yet in Sitecore 9.1.

**Comment by jaychacko** [comment]
> > > Sitecore Marketplace download is updated now. Alternatively, you can download version 1.1.0 from here, go to the Code -> Releases section and you'll find the package there. That version should address your issue.
> > 
> > 
> > great thanks ,will give it a try and let you know, any other major update i should see in 1.1.0 ?
> 
> No, besides handling the list/dropdown values correctly, and including all required Sitecore items (including the one that was missing in the original release), it doesn't include any other major updates. I've tested this module in Sitecore 9.0.x, but I haven't tested it yet in Sitecore 9.1.

great thanks

**Comment by jaychacko** [comment]
@bcalisto-oshyn update seems to have worked thanks
